export const countries = [
  { country: "Afghanistan", numberCode: "+93" },
  { country: "Albania", numberCode: "+355" },
  { country: "Algeria", numberCode: "+213" },
  { country: "American Samoa", numberCode: "+1-684" },
  { country: "Andorra", numberCode: "+376" },
  { country: "Angola", numberCode: "+244" },
  { country: "Anguilla", numberCode: "+1-264" },
  { country: "Antarctica", numberCode: "+672" },
  { country: "Antigua and Barbuda", numberCode: "+1-268" },
  { country: "Argentina", numberCode: "+54" },
  { country: "Armenia", numberCode: "+374" },
  { country: "Aruba", numberCode: "+297" },
  { country: "Australia", numberCode: "+61" },
  { country: "Austria", numberCode: "+43" },
  { country: "Azerbaijan", numberCode: "+994" },
  { country: "Bahamas", numberCode: "+1-242" },
  { country: "Bahrain", numberCode: "+973" },
  { country: "Bangladesh", numberCode: "+880" },
  { country: "Barbados", numberCode: "+1-246" },
  { country: "Belarus", numberCode: "+375" },
  { country: "Belgium", numberCode: "+32" },
  { country: "Belize", numberCode: "+501" },
  { country: "Benin", numberCode: "+229" },
  { country: "Bermuda", numberCode: "+1-441" },
  { country: "Bhutan", numberCode: "+975" },
  { country: "Bolivia", numberCode: "+591" },
  { country: "Bosnia and Herzegovina", numberCode: "+387" },
  { country: "Botswana", numberCode: "+267" },
  { country: "Brazil", numberCode: "+55" },
  { country: "British Indian Ocean Territory", numberCode: "+246" },
  { country: "British Virgin Islands", numberCode: "+1-284" },
  { country: "Brunei", numberCode: "+673" },
  { country: "Bulgaria", numberCode: "+359" },
  { country: "Burkina Faso", numberCode: "+226" },
  { country: "Burundi", numberCode: "+257" },
  { country: "Cambodia", numberCode: "+855" },
  { country: "Cameroon", numberCode: "+237" },
  { country: "Canada", numberCode: "+1" },
  { country: "Cape Verde", numberCode: "+238" },
  { country: "Cayman Islands", numberCode: "+1-345" },
  { country: "Central African Republic", numberCode: "+236" },
  { country: "Chad", numberCode: "+235" },
  { country: "Chile", numberCode: "+56" },
  { country: "China", numberCode: "+86" },
  { country: "Christmas Island", numberCode: "+61" },
  { country: "Cocos Islands", numberCode: "+61" },
  { country: "Colombia", numberCode: "+57" },
  { country: "Comoros", numberCode: "+269" },
  { country: "Cook Islands", numberCode: "+682" },
  { country: "Costa Rica", numberCode: "+506" },
  { country: "Croatia", numberCode: "+385" },
  { country: "Cuba", numberCode: "+53" },
  { country: "Curacao", numberCode: "+599" },
  { country: "Cyprus", numberCode: "+357" },
  { country: "Czech Republic", numberCode: "+420" },
  { country: "Democratic Republic of the Congo", numberCode: "+243" },
  { country: "Denmark", numberCode: "+45" },
  { country: "Djibouti", numberCode: "+253" },
  { country: "Dominica", numberCode: "+1-767" },
  { country: "Dominican Republic", numberCode: "+1-809, +1-829, +1-849" },
  { country: "East Timor", numberCode: "+670" },
  { country: "Ecuador", numberCode: "+593" },
  { country: "Egypt", numberCode: "+20" },
  { country: "El Salvador", numberCode: "+503" },
  { country: "Equatorial Guinea", numberCode: "+240" },
  { country: "Eritrea", numberCode: "+291" },
  { country: "Estonia", numberCode: "+372" },
  { country: "Ethiopia", numberCode: "+251" },
  { country: "Falkland Islands", numberCode: "+500" },
  { country: "Faroe Islands", numberCode: "+298" },
  { country: "Fiji", numberCode: "+679" },
  { country: "Finland", numberCode: "+358" },
  { country: "France", numberCode: "+33" },
  { country: "French Polynesia", numberCode: "+689" },
  { country: "Gabon", numberCode: "+241" },
  { country: "Gambia", numberCode: "+220" },
  { country: "Georgia", numberCode: "+995" },
  { country: "Germany", numberCode: "+49" },
  { country: "Ghana", numberCode: "+233" },
  { country: "Gibraltar", numberCode: "+350" },
  { country: "Greece", numberCode: "+30" },
  { country: "Greenland", numberCode: "+299" },
  { country: "Grenada", numberCode: "+1-473" },
  { country: "Guam", numberCode: "+1-671" },
  { country: "Guatemala", numberCode: "+502" },
  { country: "Guernsey", numberCode: "+44-1481" },
  { country: "Guinea", numberCode: "+224" },
  { country: "Guinea-Bissau", numberCode: "+245" },
  { country: "Guyana", numberCode: "+592" },
  { country: "Haiti", numberCode: "+509" },
  { country: "Honduras", numberCode: "+504" },
  { country: "Hong Kong", numberCode: "+852" },
  { country: "Hungary", numberCode: "+36" },
  { country: "Iceland", numberCode: "+354" },
  { country: "India", numberCode: "+91" },
  { country: "Indonesia", numberCode: "+62" },
  { country: "Iran", numberCode: "+98" },
  { country: "Iraq", numberCode: "+964" },
  { country: "Ireland", numberCode: "+353" },
  { country: "Isle of Man", numberCode: "+44-1624" },
  { country: "Israel", numberCode: "+972" },
  { country: "Italy", numberCode: "+39" },
  { country: "Ivory Coast", numberCode: "+225" },
  { country: "Jamaica", numberCode: "+1-876" },
  { country: "Japan", numberCode: "+81" },
  { country: "Jersey", numberCode: "+44-1534" },
  { country: "Jordan", numberCode: "+962" },
  { country: "Kazakhstan", numberCode: "+7" },
  { country: "Kenya", numberCode: "+254" },
  { country: "Kiribati", numberCode: "+686" },
  { country: "Kosovo", numberCode: "+383" },
  { country: "Kuwait", numberCode: "+965" },
  { country: "Kyrgyzstan", numberCode: "+996" },
  { country: "Laos", numberCode: "+856" },
  { country: "Latvia", numberCode: "+371" },
  { country: "Lebanon", numberCode: "+961" },
  { country: "Lesotho", numberCode: "+266" },
  { country: "Liberia", numberCode: "+231" },
  { country: "Libya", numberCode: "+218" },
  { country: "Liechtenstein", numberCode: "+423" },
  { country: "Lithuania", numberCode: "+370" },
  { country: "Luxembourg", numberCode: "+352" },
  { country: "Macau", numberCode: "+853" },
  { country: "Macedonia", numberCode: "+389" },
  { country: "Madagascar", numberCode: "+261" },
  { country: "Malawi", numberCode: "+265" },
  { country: "Malaysia", numberCode: "+60" },
  { country: "Maldives", numberCode: "+960" },
  { country: "Mali", numberCode: "+223" },
  { country: "Malta", numberCode: "+356" },
  { country: "Marshall Islands", numberCode: "+692" },
  { country: "Mauritania", numberCode: "+222" },
  { country: "Mauritius", numberCode: "+230" },
  { country: "Mayotte", numberCode: "+262" },
  { country: "Mexico", numberCode: "+52" },
  { country: "Micronesia", numberCode: "+691" },
  { country: "Moldova", numberCode: "+373" },
  { country: "Monaco", numberCode: "+377" },
  { country: "Mongolia", numberCode: "+976" },
  { country: "Montenegro", numberCode: "+382" },
  { country: "Montserrat", numberCode: "+1-664" },
  { country: "Morocco", numberCode: "+212" },
  { country: "Mozambique", numberCode: "+258" },
  { country: "Myanmar (Burma)", numberCode: "+95" },
  { country: "Namibia", numberCode: "+264" },
  { country: "Nauru", numberCode: "+674" },
  { country: "Nepal", numberCode: "+977" },
  { country: "Netherlands", numberCode: "+31" },
  { country: "New Caledonia", numberCode: "+687" },
  { country: "New Zealand", numberCode: "+64" },
  { country: "Nicaragua", numberCode: "+505" },
  { country: "Niger", numberCode: "+227" },
  { country: "Nigeria", numberCode: "+234" },
  { country: "Niue", numberCode: "+683" },
  { country: "Norfolk Island", numberCode: "+672" },
  { country: "North Korea", numberCode: "+850" },
  { country: "Northern Mariana Islands", numberCode: "+1-670" },
  { country: "Norway", numberCode: "+47" },
  { country: "Oman", numberCode: "+968" },
  { country: "Pakistan", numberCode: "+92" },
  { country: "Palau", numberCode: "+680" },
  { country: "Palestine", numberCode: "+970" },
  { country: "Panama", numberCode: "+507" },
  { country: "Papua New Guinea", numberCode: "+675" },
  { country: "Paraguay", numberCode: "+595" },
  { country: "Peru", numberCode: "+51" },
  { country: "Philippines", numberCode: "+63" },
  { country: "Pitcairn", numberCode: "+64" },
  { country: "Poland", numberCode: "+48" },
  { country: "Portugal", numberCode: "+351" },
  { country: "Puerto Rico", numberCode: "+1-787, +1-939" },
  { country: "Qatar", numberCode: "+974" },
  { country: "Republic of the Congo", numberCode: "+242" },
  { country: "Reunion", numberCode: "+262" },
  { country: "Romania", numberCode: "+40" },
  { country: "Russia", numberCode: "+7" },
  { country: "Rwanda", numberCode: "+250" },
  { country: "Saint Barthelemy", numberCode: "+590" },
  { country: "Saint Helena", numberCode: "+290" },
  { country: "Saint Kitts and Nevis", numberCode: "+1-869" },
  { country: "Saint Lucia", numberCode: "+1-758" },
  { country: "Saint Martin", numberCode: "+590" },
  { country: "Saint Pierre and Miquelon", numberCode: "+508" },
  { country: "Saint Vincent and the Grenadines", numberCode: "+1-784" },
  { country: "Samoa", numberCode: "+685" },
  { country: "San Marino", numberCode: "+378" },
  { country: "Sao Tome and Principe", numberCode: "+239" },
  { country: "Saudi Arabia", numberCode: "+966" },
  { country: "Senegal", numberCode: "+221" },
  { country: "Serbia", numberCode: "+381" },
  { country: "Seychelles", numberCode: "+248" },
  { country: "Sierra Leone", numberCode: "+232" },
  { country: "Singapore", numberCode: "+65" },
  { country: "Sint Maarten", numberCode: "+1-721" },
  { country: "Slovakia", numberCode: "+421" },
  { country: "Slovenia", numberCode: "+386" },
  { country: "Solomon Islands", numberCode: "+677" },
  { country: "Somalia", numberCode: "+252" },
  { country: "South Africa", numberCode: "+27" },
  {
    country: "South Georgia and the South Sandwich Islands",
    numberCode: "+500",
  },
  { country: "South Korea", numberCode: "+82" },
  { country: "South Sudan", numberCode: "+211" },
  { country: "Spain", numberCode: "+34" },
  { country: "Sri Lanka", numberCode: "+94" },
  { country: "Sudan", numberCode: "+249" },
  { country: "Suriname", numberCode: "+597" },
  { country: "Svalbard and Jan Mayen", numberCode: "+47" },
  { country: "Swaziland", numberCode: "+268" },
  { country: "Sweden", numberCode: "+46" },
  { country: "Switzerland", numberCode: "+41" },
  { country: "Syria", numberCode: "+963" },
  { country: "Taiwan", numberCode: "+886" },
  { country: "Tajikistan", numberCode: "+992" },
  { country: "Tanzania", numberCode: "+255" },
  { country: "Thailand", numberCode: "+66" },
  { country: "Togo", numberCode: "+228" },
  { country: "Tokelau", numberCode: "+690" },
  { country: "Tonga", numberCode: "+676" },
  { country: "Trinidad and Tobago", numberCode: "+1-868" },
  { country: "Tunisia", numberCode: "+216" },
  { country: "Turkey", numberCode: "+90" },
  { country: "Turkmenistan", numberCode: "+993" },
  { country: "Turks and Caicos Islands", numberCode: "+1-649" },
  { country: "Tuvalu", numberCode: "+688" },
  { country: "U.S. Virgin Islands", numberCode: "+1-340" },
  { country: "Uganda", numberCode: "+256" },
  { country: "Ukraine", numberCode: "+380" },
  { country: "United Arab Emirates", numberCode: "+971" },
  { country: "United Kingdom", numberCode: "+44" },
  { country: "United States", numberCode: "+1" },
  { country: "Uruguay", numberCode: "+598" },
  { country: "Uzbekistan", numberCode: "+998" },
  { country: "Vanuatu", numberCode: "+678" },
  { country: "Vatican", numberCode: "+379" },
  { country: "Venezuela", numberCode: "+58" },
  { country: "Vietnam", numberCode: "+84" },
  { country: "Wallis and Futuna", numberCode: "+681" },
  { country: "Western Sahara", numberCode: "+212" },
  { country: "Yemen", numberCode: "+967" },
  { country: "Zambia", numberCode: "+260" },
  { country: "Zimbabwe", numberCode: "+263" },
];
